//package form;
package rs.np.storage_manager_server.form;

import java.util.List;

import javax.swing.JDialog;

import rs.np.storage_manager_common.domain.User;
import rs.np.storage_manager_server.form.model.UserTableModel;

/**
 * {@link JDialog} klasa za prikaz aktivnih korisnika aplikacije
 * 
 * @author Milan
 */
public class ActiveUserForm extends javax.swing.JDialog {
	/**
	 * privatni atribut lista korisnika
	 */
private List<User> users;
    /**
     * Parametrizovani konstruktor
     * 
     * @param parent roditeljski Frame tipa {@link java.awt.Frame}
     * @param modal tipa boolean, predstavlja opciju modalnosti prozora
     * @param users korisnici ovog programa, kao lista korisnika
     */
    public ActiveUserForm(java.awt.Frame parent, boolean modal, List<User> users) {
        super(parent, modal);
        initComponents();
        this.users = users;
        setTitle("Active user form");
        setLocationRelativeTo(null);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblInfo.setText("Here is a list of users currently operating this program and their relevant info:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Event handler za klik na dugme cancel. Zatvara se forma
     * 
     * @param evt tipa {@link java.awt.event.ActionEvent}, dogadjaj klika na dugme
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * privatni atribut tipa {@link javax.swing.JButton}, dugme za otkazivanje (cancel)
     */
    private javax.swing.JButton btnCancel;
    /**
     * privatni atribut tipa {@link javax.swing.JScrollPane}, scroll pane prozora (za JFrame)
     */
    private javax.swing.JScrollPane jScrollPane1;
    /**
     * privatni atribut tipa {@link javax.swing.JTable}, tabela korisnika
     */
    private javax.swing.JTable jTable1;
    /**
     * privatni atribut tipa {@link javax.swing.JLabel}, labela za informacije o prikazu tabele
     */
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables

    /**
     * privatna metoda pripreme forme za rad sa korisnikom. Dodeljuje tabeli odgovarajuci model
     */
    private void prepareForm() {
        UserTableModel model = new UserTableModel(users);
        jTable1.setModel(model);
    }
}
